### PR TITLE
Add query/module productions

### PR DESCRIPTION
**Pull request by natefaubion**
I left the existing functions (`parse`, `encodeJson`, etc) to work on just `SqlF` expressions, adding `parseTop`, etc for the module/query productions. I can get rid of this distinction though and require everything to build either a `Query` or `Module`. Which would you prefer?

### CODE REVIEW

**Review by cryogenian — APPROVED** [review]
I think having `SqlTop` makes sense here, because it's an extension of the language :+1:

**Comment by garyb** [comment]
Do you think it makes sense to have a sum for `SqlTop`? I'm not sure there are many (any?) cases where either query or module are acceptable in the same place. It seems like maybe they should be separate types. Either that, or we could use a phantom type / pseudo-GADT thing, so that we don't have to pattern match `SqlTop`, as we'll already know which of the two options it is from the type.

**Comment by natefaubion** [comment]
That's a good point. I'll put them in separate types.

**Comment by natefaubion** [comment]
Done.

**Pull request merged**
